// components/Layouts/Footer.vue
<template lang="pug">
    footer.footer
        .container
            .footer__top
                a.footer__logo.col(href="/" title="Blog da Apiki")
                    img(:src="logo" alt="Blog da Apiki")

                .footer__share
                    a.footer__share-link(
                        v-for="social in social_media" 
                        v-bind:key="social.name"
                        :href="social.url"
                        target="_blank"
                    )
                        i.fab(:class="`fa-${social.name}`")

            hr.footer__hr(v-if="pages")

            .footer__bottom(v-if="pages")
                strong.footer__pages-title Institucional:
                ul.footer__pages-nav
                    li.footer__pages-li(
                        v-for="page in pages"
                        v-bind:key="`footer ${page.text}`"
                    )
                        router-link.footer__pages-link(:to="page.href") {{ page.text }}
                    
                    
                        
        
</template>
<script>

export default {
    name: 'Header',
    data() {
        return {
            logo: require('@/assets/img/apiki-logo-pb.png'),
            social_media: [
                {
                    url: 'https://www.facebook.com/ApikiWordPress',
                    name: 'facebook'
                },
                {
                    url: 'https://www.instagram.com/apikiwordpress/',
                    name: 'instagram'
                },
                {
                    url: 'https://www.youtube.com/channel/UC__ToR3hqjs1ZktdLIWqYFA',
                    name: 'youtube'
                },
                {
                    url: 'https://twitter.com/apikiWordPress',
                    name: 'twitter'
                },
                {
                    url: 'https://www.linkedin.com/company/apiki/',
                    name: 'linkedin'
                }
            ]
        }
    },
    computed: {
        pages() {
            const menu = this.$store.state.pages.pages.map( item => {
                const menu_obj = {
                    href: `/page/${item.slug}`,
                    text: item.title.rendered
                }
                return menu_obj
            })
            return menu
        }
    }
}
</script>

// blog/src/components/Footer/index.jsx
import LogoWB from '../../assets/apiki-logo-pb.png';
import FacebookLogoB from '../../assets/fb-branco.svg';
import InstagramLogoB from '../../assets/insta-branco.svg';
import LinkedinLogoB from '../../assets/linkedin-branco.svg';
import TwitterLogoB from '../../assets/twitter-branco.svg';
import YoutubeLogoB from '../../assets/youtube-branco.svg';
import './styles.css';

function Footer() {
    return (
        <footer className='footer-container'>
            <nav>
                <a href='/' className='logo'>
                    <img src={LogoWB} alt="logo apiki" />
                </a>
                <p>2022. Apiki WordPress. Todos os Direitos Reservados</p>
                <div className='social-media'>
                    <a href="https://www.facebook.com/ApikiWordPress" target='_blank' rel='noreferrer'>
                        <img src={FacebookLogoB} alt="facebook apiki" />
                    </a>
                    <a href="https://www.linkedin.com/company/apiki/"  target='_blank' rel='noreferrer' >
                        <img src={LinkedinLogoB} alt="linkedin apiki" />
                    </a>
                    <a href="https://www.instagram.com/apikiwordpress/"  target='_blank' rel='noreferrer' >
                        <img src={InstagramLogoB} alt="instagram apiki" />
                    </a>
                    <a href="https://www.youtube.com/channel/UC__ToR3hqjs1ZktdLIWqYFA"  target='_blank' rel='noreferrer' >
                        <img src={YoutubeLogoB} alt="youtube apiki" />
                    </a>
                    <a href="https://twitter.com/apikiWordPress"  target='_blank' rel='noreferrer' >
                        <img src={TwitterLogoB} alt="twitter apiki" />
                    </a>
                </div>

            </nav>
        </footer>
    );
};

export default Footer;
